### EKF LOCAL (odom -> base_link)
ekf_filter_node_odom:
  ros__parameters:
    use_sim_time: true
    frequency: 50.0
    sensor_timeout: 0.1
    two_d_mode: true
    publish_tf: true
    map_frame: map
    odom_frame: odom
    base_link_frame: base_link
    world_frame: odom

    odom0: /odom
    # Ruedas: solo velocidades.
    odom0_config: [false, false, false,
                   false, false, false,
                   true,  true,  false,
                   false, false, true,
                   false, false, false]
    odom0_differential: false
    odom0_relative: false
    odom0_queue_size: 5

    imu0: /imu/data
    # IMU: yaw rate + acceleraciones lineales horizontales (ax, ay).
    # Su ruido es bajo (sigma ~0.01 m/s2) asi que aportan mucho.
    imu0_config: [false, false, false,
                  false, false, false,
                  false, false, false,
                  false, false, true,
                  true,  true,  false]
    imu0_differential: false
    imu0_relative: false
    imu0_queue_size: 5


### EKF GLOBAL (map -> odom)
ekf_filter_node_map:
  ros__parameters:
    use_sim_time: true
    frequency: 50.0
    sensor_timeout: 0.1
    two_d_mode: true
    publish_tf: true
    map_frame: map
    odom_frame: odom
    base_link_frame: base_link
    world_frame: map

    initial_state: [0.0, 0.0, 0.0,
                    0.0, 0.0, 1.5708,
                    0.0, 0.0, 0.0,
                    0.0, 0.0, 0.0,
                    0.0, 0.0, 0.0]

    odom0: /odom
    odom0_config: [false, false, false,
                   false, false, false,
                   true,  true,  false,
                   false, false, true,
                   false, false, false]
    odom0_differential: false
    odom0_relative: false
    odom0_queue_size: 5

    imu0: /imu/data
    imu0_config: [false, false, false,
                  false, false, false,
                  false, false, false,
                  false, false, true,
                  true,  true,  false]
    imu0_differential: false
    imu0_relative: false
    imu0_queue_size: 5

    pose0: /aruco_pose
    pose0_config: [true,  true,  false,
                   false, false, true,
                   false, false, false,
                   false, false, false,
                   false, false, false]
    pose0_differential: false
    pose0_relative: false
    pose0_queue_size: 3